version: "3.8"
services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: unless-stopped
    ports:
      - "445:445"
      - "139:139"
    environment:
      - USERNAME=${SMB_USER}
      - PASSWORD=${SMB_PASS}
      - WORKGROUP=WORKGROUP
    volumes:
      - /srv/data/files:/srv/share
    command: ["-s", "media;/srv/share;yes;no;yes;all;none", "-u", "${SMB_USER};${SMB_PASS}"]
